<?php

declare(strict_types=1);

namespace Krajcik\DataBuilder\CodeCompiler;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Query\ResultSetMapping;
use Krajcik\DataBuilder\Dto\BuilderToGenerateDto;
use Krajcik\DataBuilder\Dto\Configuration;
use Krajcik\DataBuilder\PathResolver;
use Krajcik\DataBuilder\Reflection\EntityColumn;
use Krajcik\DataBuilder\Utils\DbHelper;
use Krajcik\DataBuilder\Utils\PropertyNameResolver;
use Krajcik\DataBuilder\Utils\Strings;
use Krajcik\DataBuilder\Utils\Utils;
use Nette\Database\Context;
use Nette\PhpGenerator\ClassType;
use Nette\PhpGenerator\PhpNamespace;

final class BuilderCodeCompiler
{
    private PropertyNameResolver $propertyNameResolver;

    public function __construct(
        private ?Context $db,
        private PathResolver $pathResolver,
        private Configuration $config,
    ) {
        $this->propertyNameResolver = new PropertyNameResolver();
    }

    public function precompile(
        BuilderToGenerateDto $data,
    ): ClassType {
        $namespace = new PhpNamespace(sprintf('%s\%s', $this->config->getNamespace(), $data->getClassName()));
        $namespace->addUse($data->getFullClassName());

        $namespace->addUse(EntityManagerInterface::class);
        $namespace->addUse(ResultSetMapping::class);

        $class = new ClassType($this->pathResolver->createBuilderClassName($data->getClassName()), $namespace);
        $class->setFinal();
        $class->addComment(sprintf('Automatically generated by %s.', Strings::withRootNamespace(__CLASS__)));

        $class->addProperty('parameters')
            ->setPrivate()
            ->setType($this->pathResolver->getParameterClassName($data->getClassName()));

        $class->addProperty('em')
            ->setPrivate()
            ->setType(EntityManagerInterface::class);

        return $class;
    }

    public function compile(
        BuilderToGenerateDto $data
    ): ClassType {
        $class = $this->precompile($data);

        $this->createConstructMethod($class, $data);
        $this->createGetDataMethod($class, $data);
        $this->createBuildAndSaveMethod($class, $data);
        $this->createWithMethods($class, $data);

        return $class;
    }

    private function createConstructMethod(
        ClassType            $class,
        BuilderToGenerateDto $data,
    ): void {
        $parameterType = $this->pathResolver->getParameterClassName($data->getClassName());
        $method = $class->addMethod('__construct')
            ->setPublic();

        $method
            ->addParameter('parameters')
            ->setType($parameterType);

        $method
            ->addParameter('em')
            ->setType(EntityManagerInterface::class);

        $method->addBody('$this->parameters = $parameters;');
        $method->addBody('$this->em = $em;');
    }

    private function createGetDataMethod(
        ClassType $class,
        BuilderToGenerateDto $data,
    ): void {
        $method = $class->addMethod('getData')
            ->setPrivate()
            ->setReturnType('array')
            ->addComment('@return array<string, mixed>');

        $columns = $this->db->getStructure()->getColumns($data->getTableName());

        $method->addBody('        $data = [');

        // add referenced columns
        foreach (DbHelper::sortTableColumns($columns) as $col) {
            $col = new EntityColumn($col, $data->getTableName());
            if ($col->getName() === 'id') {
                continue;
            }

            $method->addBody(sprintf(
                '    \'%s\' => $this->parameters->get%s(),',
                $col->getName(),
                Strings::firstUpper($this->propertyNameResolver->getPropertyName($col, $data)),
            ));
        }
        $method->addBody('];');
        $method->addBody('');
        $method->addBody('if ($this->parameters->getId() !== null) {');
        $method->addBody('    $data[\'id\'] = $this->parameters->getId();');
        $method->addBody('}');
        $method->addBody('');
        $method->addBody('return $data;');
    }

    private function createBuildAndSaveMethod(
        ClassType            $class,
        BuilderToGenerateDto $data,
    ): void {
        $method = $class->addMethod('buildAndSave')
            ->setPublic()
            ->setReturnType($data->getFullClassName());
        $method->addBody(sprintf('$rsm = new ResultSetMapping();'));
        $method->addBody('$parameterNames = array_map(fn(string $name) => ":" . $name, array_keys($this->getData()));');
        $method->addBody('$sql = sprintf("INSERT INTO %s (%s) VALUES (%s)", "' . $data->getTableName() . '", implode(", ", array_keys($this->getData())), implode(", ", $parameterNames) );');
        $method->addBody('$stmt = $this->em->createNativeQuery($sql, $rsm);');

        $method->addBody('foreach ($this->getData() as $name => $value) {');
        $method->addBody('    $stmt->setParameter("$name", $value);');
        $method->addBody('}');

        $method->addBody('$stmt->execute();');
        $method->addBody('$id = $this->em->getConnection()->lastInsertId();');
        $method->addBody(sprintf('$entity = $this->em->getRepository(%s::class)->find($id);', $data->getClassName()));
        $method->addBody(sprintf('assert($entity instanceof %s);', $data->getClassName()));
        $method->addBody('return $entity;');
    }


    private function createWithMethods(
        ClassType            $class,
        BuilderToGenerateDto $data,
    ): void {
        $columns = $this->db->getStructure()->getColumns($data->getTableName());

        // add referenced columns
        foreach (DbHelper::sortTableColumns($columns) as $col) {
            $col = new EntityColumn($col, $data->getTableName());
            $snakeCaseName = $this->propertyNameResolver->getPropertyName($col, $data);
            $method = $class->addMethod(sprintf('with%s', Strings::firstUpper($snakeCaseName)));
            $method
                ->setPublic()
                ->setReturnType('self')
                ->addParameter($snakeCaseName)
                    ->setType(Utils::getType($col, false))
                    ->setNullable($col->isNullable());

            $method->addBody(sprintf('        return new self('));
            $method->addBody(sprintf('    new %sParameters(', $data->getClassName()));
            foreach (DbHelper::sortTableColumns($columns) as $innerCol) {
                $innerCol = new EntityColumn($innerCol, $data->getTableName());
                if ($innerCol->getName() === $col->getName()) {
                    $columnName = $this->propertyNameResolver->getPropertyName($col, $data);
                    $method->addBody(sprintf(
                        '        %s: $%s,',
                        $columnName,
                        $columnName,
                    ));
                } else {
                    $columnName = $this->propertyNameResolver->getPropertyName($innerCol, $data);
                    $method->addBody(sprintf(
                        '        %s: $this->parameters->get%s(),',
                        $columnName,
                        Strings::firstUpper($columnName),
                    ));
                }
            }
            $method->addBody('    ),');
            $method->addBody('    $this->em,');
            $method->addBody(');');
        }
    }
}
